export const ASSET_FETCH_SUCESS = "ASSET_FETCH_SUCESS";
export const ASSET_FETCH_FAILURE = "ASSET_FETCH_FAILURE";
export const ASSET_FETCH_PENDING = "ASSET_FETCH_PENDING";
export const ASSET_FETCH_REQUEST = "ASSET_FETCH_REQUEST";
